#ifndef _CONSTANTS_HPP_DEFINED_
#define _CONSTANTS_HPP_DEFINED_

#define LINE_LOWER_BOUND 1
#define LINE_UPPER_BOUND 18
#define RELAY_LOWER_BOUND 1
#define RELAY_UPPER_BOUND 4
#define ADC_LOWER_BOUND 1
#define ADC_UPPER_BOUND 4
#define FREQUENCY_LOWER_BOUND 0
#define FREQUENCY_UPPER_BOUND 400

#define PORT_LOWER_BOUND 1001
#define PORT_UPPER_BOUND 65535

#define SERIAL_DESCRIPTOR "serial"
#define CAMERA_DESCRIPTOR "camera"

#endif
